export { default as Navbar } from './Navbar/Tete'
export { default as Header } from './Header/Header'
export { default as Ingredients } from './Ingredients/Ingredients'
export { default as Instructions } from './Instructions/Instructions'
export { default as CookingTime } from './CookingTime/CookingTime'
export { default as Message } from './Message/Message'
export { default as Loader } from './Loader/Loader'
export { default as Footer } from './Footer/Footer'