export { default as Home } from './Home'
export { default as Recipe } from './Recipe/Recipe'
export { default as Login } from './Auth/Login'
export { default as Register } from './Auth/Register'
export { default as Profile } from './Profile/Profile'